name: server

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

jobs:
  Server:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: server
        run: dotnet run --project server
