name: WsServer

on:
  workflow_dispatch:

jobs:
  WsServer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: install cloudflared
        run: |
          sudo apt update
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update && sudo apt-get install cloudflared
      - name: proxy
        run: python proxy_server.py &
      - name: cloudflared
        run: |
          sudo sysctl -w net.core.rmem_max=2500000
          sudo sysctl -w net.core.wmem_max=2500000
          cloudflared tunnel --url localhost:5081 2>&1 > cloudflared1.txt &
          sleep 10
          cat cloudflared1.txt | grep "https://.*.trycloudflare.com" | sed 's/.*\(https:\/\/.*.trycloudflare.com\).*/\1/' > cloudflared2.txt
          cat cloudflared2.txt

      - name: WsServer
        run: |
          dotnet run --project WsServer --urls http://localhost:5081
