name: WsServer

on:
  workflow_dispatch:

jobs:
  WsServer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: install cloudflared
        run: |
          sudo apt update
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update && sudo apt-get install cloudflared
      - name: proxy
        run: python proxy_server.py &  
      - name: cloudflared
        run: |
          cloudflared tunnel --url localhost:5081 2>&1 > cloudflared1.txt &
          cloudflared tunnel --url localhost:5082 2>&1 > cloudflared2.txt &
          cloudflared tunnel --url localhost:5083 2>&1 > cloudflared3.txt &
          cloudflared tunnel --url localhost:5084 2>&1 > cloudflared4.txt &
          cloudflared tunnel --url localhost:5085 2>&1 > cloudflared5.txt &
          cloudflared tunnel --url localhost:5086 2>&1 > cloudflared6.txt &
          sleep 10 
          cat cloudflared1.txt | grep "trycloudflare.com"
          cat cloudflared2.txt | grep "trycloudflare.com"
          cat cloudflared3.txt | grep "trycloudflare.com"
          cat cloudflared4.txt | grep "trycloudflare.com"
          cat cloudflared5.txt | grep "trycloudflare.com"
          cat cloudflared6.txt | grep "trycloudflare.com"
      - name: WsServer
        run: |
          dotnet run --project WsServer --urls http://localhost:5081 &
          dotnet run --project WsServer --urls http://localhost:5082 &
          dotnet run --project WsServer --urls http://localhost:5083 &
          dotnet run --project WsServer --urls http://localhost:5084 &
          dotnet run --project WsServer --urls http://localhost:5085 &
          dotnet run --project WsServer --urls http://localhost:5086 &